# check coverage, manual job
# prints output to PR comment

name: Check coverage
on:
  workflow_dispatch:
  pull_request:

jobs:
  check-coverage:
    name: Check Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install deps
        run: yarn install --frozen-lockfile && cd projects/vaults && yarn install --frozen-lockfile

      - name: Run coverage
        working-directory: projects/vaults
        run: npm run coverage
        env:
          RPC: https://rpc.ankr.com/eth/fc046d362fd7826a53b96763a67c6338518a402f7764b10eb99eebfc0543a700
          ASSET_NAME: stETH
          NETWORK: mainnet

      - name: Check coverage percentage
        working-directory: projects/vaults
        run: bash ./check-coverage.sh

      # coverage dir to artifacts
      - name: Save coveage results
        uses: actions/upload-artifact@v4
        with:
          working-directory: projects/vaults
          name: coverage report
          path: |
            coverage