name: Vault tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 'node'

      - name: Install deps
        run: yarn

      - name: Run tests
        run: npx hardhat test test/InceptionToken.js test/InceptionVault_S_EL.js test/InceptionVault_S_slashing.js test/InceptionVault_S.js
        # variable process.env.MAINNET_RPC
        env:
          MAINNET_RPC: https://rpc.ankr.com/eth
